apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: streamlit
  name: streamlit
  namespace: vllm-rocm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: streamlit
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: streamlit
    spec:
      containers:
      - image: a1abeachbum/streamlit_vllm_py@sha256:1fef004f8fe1660a793ae9ac50fe99fca7b87cddaf97644af99931738601dbb8
        name: streamlit-vllm-py-qcf4t
        ports:
        - containerPort: 8501
        env:
        - name: HERMES_URL
          value: "http://hermes-serve.hermes-lair.svc.cluster.local:8642/v1/chat/completions"
        - name: HERMES_API_KEY
          valueFrom:
            secretKeyRef:
              name: gateway-secret
              key: apiKey
      imagePullSecrets:
       - name: regcred
