apiVersion: v1
kind: Service
metadata:
  labels:
    app: streamlit
  name: streamlit
  namespace: vllm-rocm
spec:
  ports:
  - nodePort: 31182
    port: 8501
    protocol: TCP
    targetPort: 8501
  selector:
    app: streamlit
  sessionAffinity: None
  type: NodePort
